heatmaps:
  output_dir: "/data3/chensx/STAMP/outputs/reports/valid_demo/heatmaps/internal_B202326697_exp20b_split0"
  feature_dir: "/data3/chensx/STAMP/outputs/features/ourdata_conch1_5/conch1_5-49b04e14"
  wsi_dir: "/data3/chensx/Ourdata/Slides"
  checkpoint_path: "/data3/chensx/STAMP/outputs/crossval/exp20b_abmil_dann_w050/split-0/model.ckpt"
  slide_paths:
    - "B202326697.svs"
  device: "cuda"
  opacity: 0.6
  topk: 5
  bottomk: 5
